backend:
  name: github
  repo: BalintKiss2001/hungarianhighlandpiping
  branch: main
  use_graphql: true

local_backend: true
publish_mode: editorial_workflow

media_folder: "HTML/img/uploads"
public_folder: "img/uploads"

site_url: "https://booking-app-b0b82.web.app"
display_url: "https://booking-app-b0b82.web.app"
logo_url: "../logodudabalint3.png"

editor:
  preview: false

collections:
  - name: "main_pages"
    label: "Fo oldalak"
    editor:
      preview: false
    files:
      - label: "Kezdolap"
        name: "home"
        file: "HTML/index.html"
        fields:
          - label: "HTML tartalom"
            name: "body"
            widget: "code"
            default_language: "html"
            output_code_only: true
      - label: "Blog lista"
        name: "blog"
        file: "HTML/blog.html"
        fields:
          - label: "HTML tartalom"
            name: "body"
            widget: "code"
            default_language: "html"
            output_code_only: true
      - label: "Galeria"
        name: "gallery"
        file: "HTML/galéria.html"
        fields:
          - label: "HTML tartalom"
            name: "body"
            widget: "code"
            default_language: "html"
            output_code_only: true
      - label: "Hanganyagok"
        name: "audio"
        file: "HTML/hanganyagok.html"
        fields:
          - label: "HTML tartalom"
            name: "body"
            widget: "code"
            default_language: "html"
            output_code_only: true
      - label: "Kapcsolat"
        name: "contact"
        file: "HTML/oldal_3_kapcsolat.html"
        fields:
          - label: "HTML tartalom"
            name: "body"
            widget: "code"
            default_language: "html"
            output_code_only: true
      - label: "Bejelentkezes"
        name: "login"
        file: "HTML/login.html"
        fields:
          - label: "HTML tartalom"
            name: "body"
            widget: "code"
            default_language: "html"
            output_code_only: true
      - label: "Forum"
        name: "forum"
        file: "HTML/forum.html"
        fields:
          - label: "HTML tartalom"
            name: "body"
            widget: "code"
            default_language: "html"
            output_code_only: true

  - name: "blog_posts"
    label: "Blogbejegyzesek"
    editor:
      preview: false
    files:
      - label: "Mitol kulonleges a skot duda hangja?"
        name: "skot_duda_hangja"
        file: "HTML/blog-skot-duda-hangja.html"
        fields:
          - label: "HTML tartalom"
            name: "body"
            widget: "code"
            default_language: "html"
            output_code_only: true
      - label: "Skotduda eskuvon es unnepi esemenyen"
        name: "eskuvo_unnep"
        file: "HTML/blog-skotduda-eskuvo-unnep.html"
        fields:
          - label: "HTML tartalom"
            name: "body"
            widget: "code"
            default_language: "html"
            output_code_only: true
      - label: "Hogyan epul fel a gyakorlas?"
        name: "dudas_gyakorlas"
        file: "HTML/blog-dudas-gyakorlas.html"
        fields:
          - label: "HTML tartalom"
            name: "body"
            widget: "code"
            default_language: "html"
            output_code_only: true
      - label: "Ceol Mor es Ceol Beag"
        name: "ceol_mor_ceol_beag"
        file: "HTML/blog-ceol-mor-ceol-beag.html"
        fields:
          - label: "HTML tartalom"
            name: "body"
            widget: "code"
            default_language: "html"
            output_code_only: true
      - label: "Milyen dudat erdemes venni?"
        name: "duda_vasarlas"
        file: "HTML/blog-duda-vasarlas.html"
        fields:
          - label: "HTML tartalom"
            name: "body"
            widget: "code"
            default_language: "html"
            output_code_only: true
      - label: "Hogyan kezdj bele?"
        name: "duda_tanulas"
        file: "HTML/blog-duda-tanulas.html"
        fields:
          - label: "HTML tartalom"
            name: "body"
            widget: "code"
            default_language: "html"
            output_code_only: true
