backend:
  name: github
  repo: BalintKiss2001/hungarianhighlandpiping
  branch: main
  use_graphql: true

local_backend: true
publish_mode: editorial_workflow

media_folder: "HTML/img/uploads"
public_folder: "/img/uploads"

site_url: "https://booking-app-b0b82.web.app"
display_url: "https://booking-app-b0b82.web.app"
logo_url: "../logodudabalint3.png"

editor:
  preview: false

collections:
  - name: "main_pages"
    label: "Fő oldalak"
    editor:
      preview: false
    files:
      - label: "Kezdőlap"
        name: "home"
        file: "HTML/index.html"
        fields:
          - label: "HTML tartalom"
            name: "body"
            widget: "code"
            default_language: "html"
            output_code_only: true
      - label: "Blog lista"
        name: "blog"
        file: "HTML/blog.html"
        fields:
          - label: "HTML tartalom"
            name: "body"
            widget: "code"
            default_language: "html"
            output_code_only: true
      - label: "Oktatóanyagok"
        name: "materials"
        file: "HTML/oktatoanyagok.html"
        fields:
          - label: "HTML tartalom"
            name: "body"
            widget: "code"
            default_language: "html"
            output_code_only: true
      - label: "Hanganyagok"
        name: "audio"
        file: "HTML/hanganyagok.html"
        fields:
          - label: "HTML tartalom"
            name: "body"
            widget: "code"
            default_language: "html"
            output_code_only: true
      - label: "Kapcsolat"
        name: "contact"
        file: "HTML/oldal_3_kapcsolat.html"
        fields:
          - label: "HTML tartalom"
            name: "body"
            widget: "code"
            default_language: "html"
            output_code_only: true
      - label: "Bejelentkezés"
        name: "login"
        file: "HTML/login.html"
        fields:
          - label: "HTML tartalom"
            name: "body"
            widget: "code"
            default_language: "html"
            output_code_only: true
      - label: "Regisztráció"
        name: "register"
        file: "HTML/register.html"
        fields:
          - label: "HTML tartalom"
            name: "body"
            widget: "code"
            default_language: "html"
            output_code_only: true
      - label: "Fórum"
        name: "forum"
        file: "HTML/forum.html"
        fields:
          - label: "HTML tartalom"
            name: "body"
            widget: "code"
            default_language: "html"
            output_code_only: true

  - name: "blog_posts"
    label: "Blogbejegyzések"
    editor:
      preview: false
    files:
      - label: "Mitől különleges a skót duda hangja?"
        name: "skot_duda_hangja"
        file: "HTML/blog-skot-duda-hangja.html"
        fields:
          - label: "HTML tartalom"
            name: "body"
            widget: "code"
            default_language: "html"
            output_code_only: true
      - label: "Skótduda esküvőn és ünnepi eseményen"
        name: "eskuvo_unnep"
        file: "HTML/blog-skotduda-eskuvo-unnep.html"
        fields:
          - label: "HTML tartalom"
            name: "body"
            widget: "code"
            default_language: "html"
            output_code_only: true
      - label: "Hogyan épül fel a gyakorlás?"
        name: "dudas_gyakorlas"
        file: "HTML/blog-dudas-gyakorlas.html"
        fields:
          - label: "HTML tartalom"
            name: "body"
            widget: "code"
            default_language: "html"
            output_code_only: true
      - label: "Ceòl Mór és Ceòl Beag"
        name: "ceol_mor_ceol_beag"
        file: "HTML/blog-ceol-mor-ceol-beag.html"
        fields:
          - label: "HTML tartalom"
            name: "body"
            widget: "code"
            default_language: "html"
            output_code_only: true
      - label: "Milyen dudát érdemes venni?"
        name: "duda_vasarlas"
        file: "HTML/blog-duda-vasarlas.html"
        fields:
          - label: "HTML tartalom"
            name: "body"
            widget: "code"
            default_language: "html"
            output_code_only: true
      - label: "Hogyan kezdj bele?"
        name: "duda_tanulas"
        file: "HTML/blog-duda-tanulas.html"
        fields:
          - label: "HTML tartalom"
            name: "body"
            widget: "code"
            default_language: "html"
            output_code_only: true
